# Clippy configuration

# Maximum cognitive complexity
cognitive-complexity-threshold = 30

# Maximum number of lines in a function
too-many-lines-threshold = 100

# Allow certain lints for game development
allow-dbg-in-tests = true