# Rust formatting configuration (stable features only)

# Maximum line width
max_width = 100

# Use field initialization shorthand
use_field_init_shorthand = true

# Edition
edition = "2021"

# Only stable features - removed unstable ones:
# - format_code_in_doc_comments (nightly only)
# - imports_granularity (nightly only) 
# - group_imports (nightly only)