[package]
name = "boid-wars-shared"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
lightyear = { workspace = true }
serde = { workspace = true }

[dev-dependencies]